### ISSUE TITLE
[Bug]: Logging Sending spans via span buffer message without debug level

### ISSUE THREAD

**Issue by roberto-nascimento** [instana/nodejs#1316]
### Problem Description

Hello, we are using instana with fargate, we´ve noticed that even with instana env INSTANA_LOG_LEVEL=warn, and no env INSTANA_DEBUG is set, we are getting this debug log. only this debug log is appearing. It is ingesting a lot of cloudwatch log that we do not need. 

The strange thing is that on your code thia log is using debug logger.

logger.debug(`Sending spans via span buffer (no. of spans: ${spansToSend.length})`);

2024-09-05T21:19:08.479-03:00 Sending spans via span buffer (no. of spans: 5)
2024-09-05T21:19:07.477-03:00 Sending spans via span buffer (no. of spans: 20)
2024-09-05T21:19:06.476-03:00 Sending spans via span buffer (no. of spans: 20)

### Short, Self Contained Example

We are only using docker layer, no npm collector:

# INSTALL INSTANA AGENT
COPY --from=icr.io/instana/aws-fargate-nodejs:latest /instana /instana
RUN /instana/setup.sh
and starting it with in NODE_OPITIONS.

### Node.js Version

NodeJs 20

### package.json

```shell
no npm package
```

### package-lock.json

```shell
no npm package
```

**Comment by abhilash-sivan** [comment]
Hi @roberto-nascimento ,
We will take a close look and get back ASAP

**Comment by kirrg001** [comment]
We have successfully [released 3.18.0.](https://github.com/instana/nodejs/releases/tag/v3.18.0)

Could you please test the new version and let us know if the problem is resolved?
Thank you so much!

**Comment by roberto-nascimento** [comment]
Hello, thanks, we will deploy our app here to check right now.

**Comment by roberto-nascimento** [comment]
Done, no debug logs, thanks guys , you were awesome!!
