### ISSUE TITLE
[Bug]: vulnerabilities in the dependencies

### ISSUE THREAD

**Issue by sylarwang** [instana/nodejs#401]
### Problem Description

https://github.com/advisories/GHSA-93q8-gq69-wqmw 
Package: ansi-regex 
Dependency of: @instana/collector  
Path: @instana/collector > @instana/autoprofile > node-gyp > npmlog > gauge > wide-align > string-width > strip-ansi >    ansi-regex

### Node.js Version

v14.16.1

### package.json

```shell
{}
```

### package-lock.json

```shell
{}
```

**Comment by basti1302** [comment]
Thanks for the report.

See https://github.com/instana/nodejs/pull/400. This particular dependency is removed in commit https://github.com/instana/nodejs/pull/400/commits/0427eed46353d3ac43d7f3ae8181997e6661ff47. A new package version without that dependency will be released soon.

Please also take a look at the explanation in the commit comment of https://github.com/instana/nodejs/pull/400/commits/e6e2f312ec2ad127f3d7e93beceee91fda6cdf24 that points out why blindly creating bug reports like this is not appropriate.
