### ISSUE TITLE
[Bug]: Error when using Lambda Arm64 architecture with Instana Extension 

### ISSUE THREAD

**Issue by spamalot22** [instana/nodejs#596]
### Problem Description

When setting our lambda architecture to the new "Arm64" architecture, the extension fails to initialise with an unknown error:

`EXTENSION	Name: instana-lambda-extension	State: LaunchError	Events: []	Error Type: UnknownError`

Switching back to the default "x86_64" architecture resolves the issue. 
Due to the reduced costs and AWS's intention to eventually make Arm64 the default architecture, we are looking to migrate our existing functions.

There is a write-up here regarding changes required to make functions and layers compatible with the new architecture - potentially separate versions of the layer would be required for the two settings: https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-arm-based-aws-graviton2-processors/

### Short, Self Contained Example

Deploy a lambda function using the layer as usual but set the architecture to "arm64" rather than "x86_64" under the function's runtime settings.

### Node.js Version

16

### package.json

```shell
N/A
```

### package-lock.json

```shell
N/A
```

**Comment by kirrg001** [comment]
Hi! Thanks for the report.

I can confirm that arm64 is not supported yet. We will update this issue as soon as possible.

**Comment by kirrg001** [comment]
Hi there!

We have released the layer for arm64, but we have not released the docs yet. We will let you know as soon as the docs go live.

In the meanwhile you can use the layer version below and replace your region:

`arn:aws:lambda:{REGION}:410797082306:layer:instana-nodejs-arm64:1`

**Comment by spamalot22** [comment]
Many thanks for the quick turnaround on this! We will give it a try ASAP.

**Comment by kirrg001** [comment]
https://www.ibm.com/docs/en/instana-observability/current?topic=kinesis-aws-lambda-native-tracing-nodejs
Docs are live now 👍
