### ISSUE TITLE
[Bug]: Trace and Span ID missing when using @instana/collector

### ISSUE THREAD

**Issue by deepakthankachan** [instana/nodejs#644]
### Problem Description

Hi,

We were previously using the "@instana/aws-lambda" node module with manual SDK wrapping and recently switched to this layer "arn:aws:lambda:eu-west-2:410797082306:layer:instana-nodejs:120". Before the change, I could use "@instana/aws-lambda" module to get hold of the span and trace ID like so:

```
const instana = require('@instana/aws-lambda');

// inside handler
const trace = await instana.currentSpan().getTraceId(),
const span = await instana.currentSpan().getSpanId(),
```

After the switch to layer, I am now using "@instana/collector" like so

```
const instana = require('@instana/collector')(); // 1st line before any other imports

// inside handler
const trace = await instana.currentSpan().getTraceId(),
const span = await instana.currentSpan().getSpanId(),
````

When using the "@instana/collector", the currentSpan is an empty object. I am using node_externals in our webpack file to not bundle any of the dependencies too. Keep getting a warning about not having the native add ons specified [here](https://www.ibm.com/docs/de/instana-observability/current?topic=nodejs-collector-installation#native-add-ons) but I believe that they are not necessary for the span and trace? Any help is much appreciated.

Thanking You,

Deepak

### Node.js Version

Node.js 16

### package.json

```shell
{
    // OMITTED
    "dependencies": {
        "@instana/collector": "2.10.0"
     }
    // OMITTED
}
```

### package-lock.json

```shell
// OMITTED
```

**Comment by deepakthankachan** [comment]
I think this was me being a numpty. I should be using "@instana/aws-lambda" instead of "@instana/collector". Closing this

**Comment by basti1302** [comment]
Correct: Your code should still be using @instana/aws-lambda, even with the layer.  `@instana/collector` is for Node.js apps that run on a host or in a container on a host, not for Lambdas. 👍

**Comment by deepakthankachan** [comment]
@basti1302 Hi, just switched to '@instana/aws-lambda' while using the layer. Do I need to wrap the handler will instana.wrap as the trade and span id are still null even with '@instana/aws-lambda'? thanks
