### ISSUE TITLE
Log level 'INFO' messages not being sent with winston (and potentially other loggers?)

### ISSUE THREAD

**Issue by tludlow** [instana/nodejs#746]
### Problem Description

I am using the winston logger alongside '@instana/collector' and I'd like to send log messages with the level 'INFO' to my Instana dashboard so they can appear next to the traces.

This process works fine for the log messages with the level 'WARN' or 'ERROR' as in the function `@instana/core/src/tracing/instrumentation/loggers/winston.js#instrumentedCreateLogger()` there are these function calls

```
shimLevelMethod(derivedLogger, 'error', true);
shimLevelMethod(derivedLogger, 'warn', false);
```

which makes it work for those two levels, but the shim for level 'info' is not present. When I manually add the line `shimLevelMethod(derivedLogger, 'info', false);` below these two other shim function calls it works as expected!

In the documentation for the logging it has an image of the log page with 'info' level logs showing (see here: https://www.ibm.com/docs/en/instana-observability/current?topic=apis-logging#view-logging-analytics), so is this a bug or something that is intended within Instana at the moment? It does seem like the other instrumented loggers also don't include this line so maybe it's intended?

After changing this manually the dashboard works with the 'info' level so it could also be a bug. I could just keep my modified version and vendor it alongside my code but I think this would be nice for other users to also benefit from so hopefully this can be clarified and potentially fixed.

Thanks!

(Repo here: https://github.com/tludlow/instana-testing)

### Short, Self Contained Example

```
import instana from "@instana/collector";
instana({
  serviceName: "graphql-api-apollo",
  level: "debug",
});

export const logger = winston.createLogger({
  level: "info",
  defaultMeta: { service: "graphql-api" },
  transports: [
    new winston.transports.Console({ format: winston.format.simple() }),
  ],
  format: addTraceFormat(),
});

instana.setLogger(logger);


....

# This line is called anywhere but....
# I want this to show up in the analytics > logs dashboard but it doesnt (only level warn and error)
logger.info('Howdy');
```

### Node.js Version

Nodejs 18.15

### package.json

```shell
{
  "$schema": "https://json.schemastore.org/package.json",
  "version": "2.4.23",
  "name": "graphql-api",
  "main": "src/index.ts",
  "types": "src/index.ts",
  "scripts": {
    "compile": "tsc",
    "dev": "node ./dist/index.js"
  },
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@apollo/server": "^4.5.0",
    "@faker-js/faker": "^7.6.0",
    "@instana/collector": "^2.20.1",
    "body-parser": "^1.20.2",
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "global": "^4.4.0",
    "graphql": "^16.6.0",
    "winston": "^3.8.2"
  },
  "devDependencies": {
    "@swc-node/register": "^1.6.3",
    "@swc/core": "^1.3.44",
    "@types/cors": "^2.8.13",
    "@types/node": "^18.15.11",
    "typescript": "^5.0.3"
  }
}
```

### package-lock.json

```shell
File too long when pasted

See repo here: https://github.com/tludlow/instana-testing
```

**Comment by tludlow** [comment]
Other logger files here also have similar behaviour where they dont include shims for the 'info' levels:

@instana/core/src/tracing/instrumentation/loggers

**Comment by tludlow** [comment]
Further to the above comments:

I have made the logs of level 'INFO' appear in my dashboard by changing the file found at: `@instana/core/src/tracing/instrumentation/loggers/winston.js` in the following ways.

This basically allows the 'INFO' level to be traced, provides the shim and then passes the level down to the `createSpan()` so that it can be sent along side the span data.

You can see the changes here: https://gist.github.com/tludlow/e2c6fc6d570a5e93112c70ce3165e405/revisions
(bottom revision is the current winston.js file and the top revision are my changes)

As this a common issue among the other loggers (from what I can see in the code within the other files found at `@instana/core/src/tracing/instrumentation/loggers/` it would be nice to have some clarity on whether or not this is a bug or not.

**Comment by basti1302** [comment]
This works as designed.

> In the documentation for the logging it has an image of the log page with 'info' level logs showing
> (see here: https://www.ibm.com/docs/en/instana-observability/current?topic=apis-logging#view-logging-analytics),
> so is this a bug or something that is intended within Instana at the moment? It does seem like the other
> instrumented loggers also don't include this line so maybe it's intended?

As a general rule, Instana tracers only capture log spans for logs with severity "warn" or higher. Thus, log messages collected by a tracers will only have messages with severity "warn" or higher show up in logging analytics. This is documented here: https://www.ibm.com/docs/en/instana-observability/current?topic=instana-monitoring-applications#log-messages.

> Note that log messages with a severity lower than WARN are not tracked.

Logs collected from other sources do not have that restriction. That is the reason why log messages with level "info" can show up in logging analytics.

Kind regards

  Bastian
